springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  redoc:
    enabled: true
    path: /redoc
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
#logging:
#  level:
#    org.hibernate.orm.mapping: DEBUG
#    org.hibernate.boot.model.internal: DEBUG

server:
  port: 9001

seeder:
  employee:
    enabled: true  # Enable employee seeder to create admin user
  customer:
    enabled: true  # Enable customer seeder to create internet banking user
  policy:
    enabled: true
  security-question:
    enabled: true

security:
  allowed-domains:
    map:
      BACKOFFICE:
        - "192.168.100.97:9000"
        - "localhost"
      INTERNET_BANKING:
        - "192.168.100.97:9000"
        - "localhost"
      MOBILE_BANKING:
        - "localhost:44000"

shiva:
  api-doc:
    servers: ${GW_ADDRESS}${spring.mvc.servlet.path},http://localhost:${server.port}${spring.mvc.servlet.path}