spring:
  jpa:
    hibernate:
      ddl-auto: validate # It's good practice to be explicit, even if it's the same as the base.

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  server:
    port: 7002

server:
  port: 7001
