springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  redoc:
    enabled: true
    path: /redoc
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always


server:
  port: 9001

security:
  allowed-domains:
    map:
      BACKOFFICE:
        - "localhost:42000"
      INTERNET_BANKING:
        - "localhost:43000"
      MOBILE_BANKING:
        - "localhost:44000"
