spring:
  jpa:
    hibernate:
      ddl-auto: validate # It's good practice to be explicit, even if it's the same as the base.

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:6001}

server:
  port: ${SERVER_PORT:7001}

seeder:
  employee:
    enabled: true
  policy:
    enabled: true
  security-question:
    enabled: true

security:
  allowed-domains:
    map:
      BACKOFFICE:
        - "${BACKOFFICE_PUBLIC_HOST}"
        - "${BACKOFFICE_PUBLIC_HOST_ALIAS:${BACKOFFICE_PUBLIC_HOST}}"
      INTERNET_BANKING:
        - "${INTERNET_BANKING_PUBLIC_HOST}"
      MOBILE_BANKING:
        - "${MOBILE_BANKING_PUBLIC_HOST:${INTERNET_BANKING_PUBLIC_HOST}}"
